# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f333ad17d767ced50725025fd77bcfeacc7db403e93727e66c08fc99822f6553bb37bffbf119341f0a36a3ed113a9469e532d5edc6fdf94d5ff2a85b95a86baa

test:
  secret_key_base: 955e8066e37607715c0bd7e8e26b2cc200c8213d78ea0c5050ea4f3793c3339c6b4051b8f0eea946bf965e707303cde50bacda87464f5d0e6fd08cd0d3daf6dc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
